/*---------------------------------------------------------------------------
  GAUSS.C
	  ГЕНЕРАТОР ПСЕВДОСЛУЧАЙНЫХ ЧИСЕЛ ПО НОРМАЛЬНОМУ ЗАКОНУ
  Автор	 : перевод на С выполнил Пасынков В.В.
  Версия : 01.00 / 15.04.1994 /
---------------------------------------------------------------------------*/
#include <stdio.h>
#include <math.h>

#include "ssp.h"
/*     ..................................................................

        SUBROUTINE GAUSS

        PURPOSE
           COMPUTES A NORMALLY DISTRIBUTED RANDOM NUMBER WITH A GIVEN
	   MEAN AND STANDARD DEVIATION

        USAGE
	   GAUSS(IX,S,AM,V)

        DESCRIPTION OF PARAMETERS
	   IX -IX MUST CONTAIN AN ODD INTEGER NUMBER WITH NINE OR
               LESS DIGITS ON THE FIRST ENTRY TO GAUSS. THEREAFTER
               IT WILL CONTAIN A UNIFORMLY DISTRIBUTED INTEGER RANDOM
               NUMBER GENERATED BY THE SUBROUTINE FOR USE ON THE NEXT
	       ENTRY TO THE SUBROUTINE.
           S  -THE DESIRED STANDARD DEVIATION OF THE NORMAL
               DISTRIBUTION.
           AM -THE DESIRED MEAN OF THE NORMAL DISTRIBUTION
	   V  -THE VALUE OF THE COMPUTED NORMAL RANDOM VARIABLE

        REMARKS
           THIS SUBROUTINE USES RANDU WHICH IS MACHINE SPECIFIC

        SUBROUTINES AND FUNCTION SUBPROGRAMS REQUIRED
	   RANDU

	METHOD
	   USES 12 UNIFORM RANDOM NUMBERS TO COMPUTE NORMAL RANDOM
	   NUMBERS BY CENTRAL LIMIT THEOREM. THE RESULT IS THEN
	   ADJUSTED TO MATCH THE GIVEN MEAN AND STANDARD DEVIATION.
	   THE UNIFORM RANDOM NUMBERS COMPUTED WITHIN THE SUBROUTINE
	   ARE FOUND BY THE POWER RESIDUE METHOD.

     ..................................................................
 */

double  gauss(long *ix,double s,double am)
{
long iy;
int i;
double a, y, v;
if( (*ix)==0L)
  (*ix)= 314159265L;
iy=0L;
a = 0.0;y=0.0;
for( i = 1; i <= 12; i++ )
	{
	y=randu( (*ix) , &iy); (*ix) = iy;
/*  y=urand(ix);    y=randm(); разные датчики СЧ */
	a = a + y;
	}
v = (a - 6.0)*s + am;
return v;
}

